services:
  db:
    image: mongo
    container_name: mongodb
    restart: on-failure
    hostname: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - 27017:27017

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app

  redis:
    image: redis:latest
    restart: on-failure
    container_name: redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
