services:
  test_db:
    image: mongo
    container_name: mongodb-test
    restart: on-failure
    hostname: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - 27017:27017

  test_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: fastapi-app-test
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app