services:
  test_db:
    image: mongo
    container_name: mongodb-test
    hostname: "${MONGO_TEST_HOST}"
    restart: on-failure
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_TEST_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_TEST_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_TEST_DB}
    command: --port 27018
    ports:
      - "${MONGO_TEST_PORT}:27018"


  test_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: fastapi-app-test
    restart: on-failure
    ports:
      - "${APP_TEST_PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
